version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region cn-northwest-1 )
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t cb-repo:v1 .
      - docker tag cb-repo:v1  012493288977.dkr.ecr.cn-northwest-1.amazonaws.com.cn/cb-repo:v1
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 012493288977.dkr.ecr.cn-northwest-1.amazonaws.com.cn/cb-repo:v1
