version: 0.2
#https://docs.aws.amazon.com/codebuild/latest/userguide/sample-docker.html
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region cn-northwest-1 )
      #- $(aws ecr get-login --no-include-email --region us-west-1 )
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t cb-repo:v1 .
      - docker tag cb-repo:v1  012493288977.dkr.ecr.cn-northwest-1.amazonaws.com.cn/cb-repo:v1
      #- docker tag cb-repo:v1  373384066178.dkr.ecr.us-west-1.amazonaws.com/cb-repo:v1
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 012493288977.dkr.ecr.cn-northwest-1.amazonaws.com.cn/cb-repo:v1
      #- docker push 373384066178.dkr.ecr.us-west-1.amazonaws.com/cb-repo:v1
